language: node_js

sudo: false

cache:
    yarn: true
    directories:
        - node_modules

env:
    global:
        - NODE_ENV=test
        - TZ=Europe/Paris

node_js:
    - "8.10"

script:
    - yarn lint
    - yarn test
