os: linux
dist: xenial
language: node_js

# avoid double Travis build when the PR is created on upstream
if: |
    type = pull_request OR \
    branch = master

env:
    global:
        - NODE_ENV=test
        - TZ=Europe/Paris

script:
    - yarn lint
    - yarn test
