name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CI: true
  TZ: 'Europe/Paris'
  NODE_ENV: 'test'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: install
        run: yarn install

      - name: lint
        run: yarn lint

      - name: test
        run: yarn test
